export default {
  powers:[
    {
      code:1,
      nodeType:1,
      icon:'question',
      link:'/',
      name:'一级菜单1'
    },
    {
      code:2,
      nodeType:1,
      icon:'area-chart',
      name:'一级菜单2',
      link:'/secondP',
      children:[]
    },
    {
      code:3,
      nodeType:1,
      name:'一级菜单3',
      icon:'scan',
      link:'/thirdP',
      children:[
        {
          code:301,
          nodeType:2,
          name:'二级菜单3-1',
          link:'/',
        },
        {
          code:302,
          nodeType:2,
          name:'二级菜单3-2',
          link:'/',
          children:[]
        },
        {
          code:303,
          nodeType:3,
          name:'二级菜单3-3',
          link:'/',
          children:[
            {
              code:30301,
              nodeType:303,
              name:'三级菜单3-3-1',
              link:'/',
            }
          ]
        }
      ]
    }
  ]
}